import { Product } from './interface/table.interface';

export const ELEMENT_DATA: Product[] = [
  {
    image: 'https://via.placeholder.com/50',
    name: 'Продукт 1',
    discount: 10,
    price: 100,
    sku: 'SKU001',
    token: 'abc123',
    productID: 1,
    isActive: true,
    countryCode: 'us',
    itemUrl: 'https://example.com/product-1',
    tags: ['електроніка', 'новинка'],
  },
  {
    image: 'https://via.placeholder.com/50',
    name: 'Продукт 2',
    discount: 5,
    price: 150,
    sku: 'SKU002',
    token: 'def456',
    productID: 2,
    isActive: false,
    countryCode: 'ca',
    itemUrl: 'https://example.com/product-2',
    tags: ['меблі', 'популярне'],
  },
  {
    image: 'https://via.placeholder.com/50',
    name: 'Продукт 3',
    discount: 15,
    price: 200,
    sku: 'SKU003',
    token: 'ghi789',
    productID: 3,
    isActive: true,
    countryCode: 'uk',
    itemUrl: 'https://example.com/product-3',
    tags: ['одяг', 'розпродаж'],
  },
  {
    image: 'https://via.placeholder.com/50',
    name: 'Продукт 4',
    discount: 20,
    price: 250,
    sku: 'SKU004',
    token: 'jkl012',
    productID: 4,
    isActive: true,
    countryCode: 'us',
    itemUrl: 'https://example.com/product-4',
    tags: ['електроніка', 'акція'],
  },
  {
    image: 'https://via.placeholder.com/50',
    name: 'Продукт 5',
    discount: 0,
    price: 300,
    sku: 'SKU005',
    token: 'mno345',
    productID: 5,
    isActive: false,
    countryCode: 'de',
    itemUrl: 'https://example.com/product-5',
    tags: ['меблі', 'розпродаж'],
  },
  {
    image: 'https://via.placeholder.com/50',
    name: 'Продукт 6',
    discount: 25,
    price: 400,
    sku: 'SKU006',
    token: 'pqr678',
    productID: 6,
    isActive: true,
    countryCode: 'us',
    itemUrl: 'https://example.com/product-6',
    tags: ['побутова техніка', 'акція'],
  },
  {
    image: 'https://via.placeholder.com/50',
    name: 'Продукт 7',
    discount: 8,
    price: 500,
    sku: 'SKU007',
    token: 'stu901',
    productID: 7,
    isActive: true,
    countryCode: 'ca',
    itemUrl: 'https://example.com/product-7',
    tags: ['електроніка', 'новинка'],
  },
  {
    image: 'https://via.placeholder.com/50',
    name: 'Продукт 8',
    discount: 12,
    price: 600,
    sku: 'SKU008',
    token: 'vwx234',
    productID: 8,
    isActive: false,
    countryCode: 'uk',
    itemUrl: 'https://example.com/product-8',
    tags: ['меблі', 'популярне'],
  },
  {
    image: 'https://via.placeholder.com/50',
    name: 'Продукт 9',
    discount: 18,
    price: 700,
    sku: 'SKU009',
    token: 'yz1234',
    productID: 9,
    isActive: true,
    countryCode: 'us',
    itemUrl: 'https://example.com/product-9',
    tags: ['одяг', 'новинка'],
  },
  {
    image: 'https://via.placeholder.com/50',
    name: 'Продукт 10',
    discount: 30,
    price: 800,
    sku: 'SKU010',
    token: 'abc567',
    productID: 10,
    isActive: false,
    countryCode: 'de',
    itemUrl: 'https://example.com/product-10',
    tags: ['побутова техніка', 'акція'],
  },
  {
    image: 'https://via.placeholder.com/50',
    name: 'Продукт 11',
    discount: 14,
    price: 900,
    sku: 'SKU011',
    token: 'def890',
    productID: 11,
    isActive: true,
    countryCode: 'ca',
    itemUrl: 'https://example.com/product-11',
    tags: ['електроніка', 'розпродаж'],
  },
  {
    image: 'https://via.placeholder.com/50',
    name: 'Продукт 12',
    discount: 7,
    price: 1000,
    sku: 'SKU012',
    token: 'ghi123',
    productID: 12,
    isActive: false,
    countryCode: 'uk',
    itemUrl: 'https://example.com/product-12',
    tags: ['меблі', 'популярне'],
  },
  {
    image: 'https://via.placeholder.com/50',
    name: 'Продукт 13',
    discount: 6,
    price: 1100,
    sku: 'SKU013',
    token: 'jkl456',
    productID: 13,
    isActive: true,
    countryCode: 'us',
    itemUrl: 'https://example.com/product-13',
    tags: ['одяг', 'новинка'],
  },
  {
    image: 'https://via.placeholder.com/50',
    name: 'Продукт 14',
    discount: 22,
    price: 1200,
    sku: 'SKU014',
    token: 'mno789',
    productID: 14,
    isActive: true,
    countryCode: 'de',
    itemUrl: 'https://example.com/product-14',
    tags: ['побутова техніка', 'акція'],
  },
  {
    image: 'https://via.placeholder.com/50',
    name: 'Продукт 15',
    discount: 11,
    price: 1300,
    sku: 'SKU015',
    token: 'pqr012',
    productID: 15,
    isActive: false,
    countryCode: 'ca',
    itemUrl: 'https://example.com/product-15',
    tags: ['електроніка', 'розпродаж'],
  },
  {
    image: 'https://via.placeholder.com/50',
    name: 'Продукт 16',
    discount: 19,
    price: 1400,
    sku: 'SKU016',
    token: 'stu345',
    productID: 16,
    isActive: true,
    countryCode: 'uk',
    itemUrl: 'https://example.com/product-16',
    tags: ['меблі', 'популярне'],
  },
  {
    image: 'https://via.placeholder.com/50',
    name: 'Продукт 17',
    discount: 23,
    price: 1500,
    sku: 'SKU017',
    token: 'vwx678',
    productID: 17,
    isActive: false,
    countryCode: 'us',
    itemUrl: 'https://example.com/product-17',
    tags: ['одяг', 'новинка'],
  },
  {
    image: 'https://via.placeholder.com/50',
    name: 'Продукт 18',
    discount: 5,
    price: 1600,
    sku: 'SKU018',
    token: 'yz9012',
    productID: 18,
    isActive: true,
    countryCode: 'de',
    itemUrl: 'https://example.com/product-18',
    tags: ['побутова техніка', 'акція'],
  },
  {
    image: 'https://via.placeholder.com/50',
    name: 'Продукт 19',
    discount: 17,
    price: 1700,
    sku: 'SKU019',
    token: 'abc3456',
    productID: 19,
    isActive: false,
    countryCode: 'ca',
    itemUrl: 'https://example.com/product-19',
    tags: ['електроніка', 'розпродаж'],
  },
  {
    image: 'https://via.placeholder.com/50',
    name: 'Продукт 20',
    discount: 24,
    price: 1800,
    sku: 'SKU020',
    token: 'def7890',
    productID: 20,
    isActive: true,
    countryCode: 'uk',
    itemUrl: 'https://example.com/product-20',
    tags: ['меблі', 'популярне'],
  },
];
