import { PeriodicElement } from "./interface/table.interface";

export const ELEMENT_DATA: PeriodicElement[] = [
  {
    name: 'Laptop',
    sku: '12345-AB',
    price: 999.99,
    country: 'us',
    tags: ['electronics', 'computer', 'tech'],
    id: 'ID001',
  },
  {
    name: 'Smartphone',
    sku: '98765-CD',
    price: 799.99,
    country: 'kr',
    tags: ['mobile', 'gadgets', 'tech'],
    id: 'ID002',
  },
  {
    name: 'Headphones',
    sku: '54321-EF',
    price: 199.99,
    country: 'de',
    tags: ['audio', 'music', 'tech'],
    id: 'ID003',
  },
  {
    name: 'Gaming Console',
    sku: '11223-GH',
    price: 499.99,
    country: 'jp',
    tags: ['gaming', 'console', 'entertainment'],
    id: 'ID004',
  },
  {
    name: 'Tablet',
    sku: '33445-IJ',
    price: 349.99,
    country: 'cn',
    tags: ['electronics', 'tablet', 'tech'],
    id: 'ID005',
  },
  {
    name: 'Smartwatch',
    sku: '55667-KL',
    price: 249.99,
    country: 'us',
    tags: ['wearables', 'tech', 'gadgets'],
    id: 'ID006',
  },
  {
    name: 'Camera',
    sku: '77889-MN',
    price: 1299.99,
    country: 'jp',
    tags: ['photography', 'camera', 'tech'],
    id: 'ID007',
  },
  {
    name: 'Electric Toothbrush',
    sku: '99001-OP',
    price: 89.99,
    country: 'us',
    tags: ['health', 'gadgets', 'wellness'],
    id: 'ID008',
  },
  {
    name: 'Wireless Charger',
    sku: '11223-QR',
    price: 29.99,
    country: 'cn',
    tags: ['accessories', 'tech', 'mobile'],
    id: 'ID009',
  },
  {
    name: 'Coffee Maker',
    sku: '33445-ST',
    price: 149.99,
    country: 'it',
    tags: ['kitchen', 'appliances', 'coffee'],
    id: 'ID0010',
  },
];
